name: Bug Report
description: File a report about a bug you have found. Do not use it for support requests.
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: description
    attributes:
      label: Describe the issue.
      placeholder: Provide as many details as you can, along with expected behavior.
    validations:
      required: true
  - type: dropdown
    id: component
    attributes:
      label: Component
      description: What component of Spark⚡️Bot is this affecting?
      options:
        - Config
        - Logging
        - Scheduled Events
        - Gateway Events
        - Commands
        - Database support
        - Localization
        - Official Plugins
        - Unofficial Plugins
      default: 0
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: Please certify you have completed the following checks.
      options:
        - label: I have searched for this issue and confirm it is not a duplicate
          required: true
        - label: This is a bug and not a request for help or support
          required: true
        - label: I would like to submit a PR to resolve this issue
