name: 💡 Feature Request / Idea Submission
description: Suggest a new feature, idea or change to the current codebase.
title: '<Component>: <Short description of your suggestion>'
labels: ["feature", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to let us know what would make Spark⚡️Bot better.  Please complete all fields to help us fully evaluate the request.
  - type: textarea
    id: description
    attributes:
      label: Feature description
      placeholder: Please provide a detailed description of the feature you are looking for.
    validations:
      required: true
  - type: dropdown
    id: component
    attributes:
      label: Component
      description: What component(s) of Spark⚡️Bot does this feature apply to?
      multiple: true
      options:
        - Commands
        - Message Components
        - Scheduled Events
        - Gateway Events
        - Configuration
        - Logging
        - Secrets management
        - Localization
        - Database support
        - Documentation
        - Official Plugins
        - Unofficial Plugins
        - Other
    validations:
      required: true
  - type: checkboxes
    id: contributing
    attributes:
      label: Checks
      description: Please certify you have completed the following checks.
      options:
        - label: I have thoroughly read and understand [Code of Conduct](https://github.com/SparkBotDev/.github/blob/main/CODE_OF_CONDUCT.md) and [Contributing Guide](https://github.com/SparkBotDev/.github/blob/main/CONTRIBUTING.md).
          required: true
        - label: "The format of the title follows <Component>: <Short description of your suggestion>"
          required: true
        - label: I have [searched](https://github.com/SparkBotDev/SparkBot/issues?q=is%3Aissue+label%3Afeature) for this feature and confirm it is not a duplicate.
          required: true
        - label: I would like to be assigned to implement this feature if it is approved.
  - type: input
    id: contact
    attributes:
      label: (Optional) Discord Username
      description: Optionally provide your discord name to help coordinate changes there if necessary.
    validations:
      required: false